### ISSUE TITLE
Can it update the same comment that triggered it?

### ISSUE THREAD

**Issue by gep13** [micnncim/action-lgtm-reaction#13]
Firstly, let me say thank you for this addin, love it!

Quick question... rather than adding a new comment into the PR, would it be possible to update the comment that triggered it?  This would be solely for the intention of reducing the notifications that are generated on a PR/Issue.

Thanks again!

**Comment by micnncim** [comment]
Thank you for adding this addin!

Your idea sounds great😇 I'll work to update this addin!

**Comment by gep13** [comment]
>@micnncim said...
Your idea sounds great😇 I'll work to update this addin!

That is great news!  Let me know if you need a beta tester :-)

I have also seen this [action](https://github.com/sobolevn/restrict-cursing-action) which seems to update a comment in place. Thought it might be useful to you.

**Comment by gep13** [comment]
As a side question...

Is it possible to also allow triggering of this action with a comment associated with a PR approval?  On this PR:

https://github.com/cake-build/website/pull/770#issuecomment-542107434

You will see that I write `LGTM!` on the PR approval, but the action wasn't triggered.  It was only on the additional `LGTM!` that I added as a direct issue comment that the action was triggered.  Any ideas?

**Comment by micnncim** [comment]
Thank you for your thought.

It's possible to trigger this action with review comments. And I'll do.

Also I have some ideas about features:

- support multiple trigger comments
  e.g.) ['lgtm', 'good job']
- support regexp as trigger comments
  e.g.) ['^LGTM.*', '[nN]ice [wW]ork']
- give option users can approve PR with trigger comment

I wanna hear your opinion or additional ideas😇

**Comment by micnncim** [comment]
And also, I'm glad to hear you introduced this action! If you don't mind, please give a PR adding the project names to this project's README😇

**Comment by micnncim** [comment]
I've just implement some features we talked about.

- Override (update) a trigger comment 
  - https://github.com/micnncim/action-lgtm-reaction/pull/14
- Trigger PR reviews
  - https://github.com/micnncim/action-lgtm-reaction/pull/15
- Support regexp and multiple triggers
  - https://github.com/micnncim/action-lgtm-reaction/pull/17

Thank you for your feedback!

**Comment by gep13** [comment]
@micnncim this is great news!  Thank you so much for taking the time to do this.  I will take this for a spin with the next PR that I review, and I will let you know how I get on.

**Comment by gep13** [comment]
>@micnncim said...
If you don't mind, please give a PR adding the project names to this project's README😇

Done... https://github.com/micnncim/action-lgtm-reaction/pull/19

**Comment by gep13** [comment]
>@micnncim said...
give option users can approve PR with trigger comment

This isn't something that I think I would make use of, since normally I will be reviewing the files in the PR, and then mark as approved with comment, rather than commenting on a PR first.  I can see how this might be useful to some people though.

**Comment by micnncim** [comment]
> This isn't something that I think I would make use of, since normally I will be reviewing the files in the PR, and then mark as approved with comment, rather than commenting on a PR first.

I see. I also think so. Thank you :)

**Comment by micnncim** [comment]
@gep13 If you have any idea, request or question, don't mind to create an issue 👍
