### ISSUE TITLE
unable to get random lgtm url: no giphy

### ISSUE THREAD

**Issue by gep13** [micnncim/action-lgtm-reaction#27]
@micnncim do you have any idea about what could be going on here:

![image](https://user-images.githubusercontent.com/1271146/67070074-f75ccd80-f176-11e9-956d-409c57fd633a.png)

This is when running on the Cake Website:

https://github.com/cake-build/website/blob/master/.github/workflows/lgtm.yml

Thanks

**Comment by micnncim** [comment]
I'll trace the cause and fix the bug.

**Comment by micnncim** [comment]
@gep13 So sorry for late. Fixed the issue!

**Comment by gep13** [comment]
@micnncim that is great news! Is there a new version available?

**Comment by micnncim** [comment]
@gep13 yes, the fixed version v0.6.0 is available :+1:
